language: python
python:
    - "3.4"
    - "3.5"
    - "3.6"
    - "nightly"
install:
    - "pip install ."
    - "pip install -r requirements_tests.txt"
script:
    - "python -m pytest --cov=gemstone tests"
after_success:
    - "coveralls -i"

branches:
  only:
    - master