language: python
python:
    - "3.4"
    - "3.5"
    - "3.6"
install:
    - "pip install ."
    - "pip install pytest coverage python-coveralls"
script:
    - "coverage run --source=gemstone -m pytest tests"
after_success:
    - "coveralls -i"

branches:
  only:
    - master