language: python
python:
    - "3.4"
    - "3.5"
    - "3.6"
    - "nightly"
install:
    - "pip install ."
    - "pip install pytest coverage python-coveralls"
script:
    - "pytest --cov=gemstone --cov-report=html tests"
after_success:
    - "coveralls -i"

branches:
  only:
    - master