environment:
  matrix:
    - PYTHON: "C:\\Python34"
    - PYTHON: "C:\\Python34-x64"
    - PYTHON: "C:\\Python35"
    - PYTHON: "C:\\Python35-x64"
    - PYTHON: "C:\\Python36"
    - PYTHON: "C:\\Python36-x64"

build: off

install:
  - "%PYTHON%\\python.exe setup.py install"

test_script:
  - "%PYTHON%\\python.exe -m unittest discover tests"
